[theme]
primaryColor = "#6C63FF"              
backgroundColor = "#FFFFFF"           
secondaryBackgroundColor = "#F4F6F8"  
textColor = "#1F2937"                 
font = "sans serif"                   
